# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(559, 460, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(559, 400, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(559, 350, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 350, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 400, 91, 20))
        self.label_4.setObjectName("label_4")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 100, 269, 1011))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_128 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_128.setObjectName("label_128")
        self.verticalLayout_5.addWidget(self.label_128)
        self.label_129 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_5.addWidget(self.label_129)
        self.label_130 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_5.addWidget(self.label_130)
        self.label_131 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_131.setObjectName("label_131")
        self.verticalLayout_5.addWidget(self.label_131)
        self.label_132 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_132.setObjectName("label_132")
        self.verticalLayout_5.addWidget(self.label_132)
        self.label_133 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_133.setObjectName("label_133")
        self.verticalLayout_5.addWidget(self.label_133)
        self.label_134 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_134.setObjectName("label_134")
        self.verticalLayout_5.addWidget(self.label_134)
        self.label_135 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_135.setObjectName("label_135")
        self.verticalLayout_5.addWidget(self.label_135)
        self.label_136 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_136.setObjectName("label_136")
        self.verticalLayout_5.addWidget(self.label_136)
        self.label_137 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_137.setObjectName("label_137")
        self.verticalLayout_5.addWidget(self.label_137)
        self.label_138 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_138.setObjectName("label_138")
        self.verticalLayout_5.addWidget(self.label_138)
        self.label_139 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_139.setObjectName("label_139")
        self.verticalLayout_5.addWidget(self.label_139)
        self.label_140 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_140.setObjectName("label_140")
        self.verticalLayout_5.addWidget(self.label_140)
        self.label_141 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_141.setObjectName("label_141")
        self.verticalLayout_5.addWidget(self.label_141)
        self.label_142 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_142.setObjectName("label_142")
        self.verticalLayout_5.addWidget(self.label_142)
        self.label_143 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_143.setObjectName("label_143")
        self.verticalLayout_5.addWidget(self.label_143)
        self.label_144 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_144.setObjectName("label_144")
        self.verticalLayout_5.addWidget(self.label_144)
        self.label_145 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_145.setObjectName("label_145")
        self.verticalLayout_5.addWidget(self.label_145)
        self.label_146 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_146.setObjectName("label_146")
        self.verticalLayout_5.addWidget(self.label_146)
        self.label_147 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_147.setObjectName("label_147")
        self.verticalLayout_5.addWidget(self.label_147)
        self.label_148 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_148.setObjectName("label_148")
        self.verticalLayout_5.addWidget(self.label_148)
        self.label_149 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_149.setObjectName("label_149")
        self.verticalLayout_5.addWidget(self.label_149)
        self.label_150 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_150.setObjectName("label_150")
        self.verticalLayout_5.addWidget(self.label_150)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_151 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_151.setObjectName("label_151")
        self.verticalLayout_6.addWidget(self.label_151)
        self.label_152 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_152.setObjectName("label_152")
        self.verticalLayout_6.addWidget(self.label_152)
        self.label_153 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_153.setObjectName("label_153")
        self.verticalLayout_6.addWidget(self.label_153)
        self.label_154 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_154.setObjectName("label_154")
        self.verticalLayout_6.addWidget(self.label_154)
        self.label_155 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_155.setObjectName("label_155")
        self.verticalLayout_6.addWidget(self.label_155)
        self.label_156 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_156.setObjectName("label_156")
        self.verticalLayout_6.addWidget(self.label_156)
        self.label_157 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_157.setObjectName("label_157")
        self.verticalLayout_6.addWidget(self.label_157)
        self.label_158 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_158.setObjectName("label_158")
        self.verticalLayout_6.addWidget(self.label_158)
        self.label_159 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_159.setObjectName("label_159")
        self.verticalLayout_6.addWidget(self.label_159)
        self.label_160 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_160.setObjectName("label_160")
        self.verticalLayout_6.addWidget(self.label_160)
        self.label_161 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_161.setObjectName("label_161")
        self.verticalLayout_6.addWidget(self.label_161)
        self.label_162 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_162.setObjectName("label_162")
        self.verticalLayout_6.addWidget(self.label_162)
        self.label_163 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_163.setObjectName("label_163")
        self.verticalLayout_6.addWidget(self.label_163)
        self.label_164 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_164.setObjectName("label_164")
        self.verticalLayout_6.addWidget(self.label_164)
        self.label_165 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_165.setObjectName("label_165")
        self.verticalLayout_6.addWidget(self.label_165)
        self.label_166 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_166.setObjectName("label_166")
        self.verticalLayout_6.addWidget(self.label_166)
        self.label_167 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_167.setObjectName("label_167")
        self.verticalLayout_6.addWidget(self.label_167)
        self.label_168 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_168.setObjectName("label_168")
        self.verticalLayout_6.addWidget(self.label_168)
        self.label_169 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_169.setObjectName("label_169")
        self.verticalLayout_6.addWidget(self.label_169)
        self.label_170 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_170.setObjectName("label_170")
        self.verticalLayout_6.addWidget(self.label_170)
        self.label_171 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_171.setObjectName("label_171")
        self.verticalLayout_6.addWidget(self.label_171)
        self.label_172 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_172.setObjectName("label_172")
        self.verticalLayout_6.addWidget(self.label_172)
        self.label_173 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_173.setObjectName("label_173")
        self.verticalLayout_6.addWidget(self.label_173)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_6)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 510, 171, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 20, 521, 271))
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 520, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(650, 520, 72, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(680, 350, 72, 15))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(680, 400, 72, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 310, 211, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(670, 310, 72, 15))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(570, 310, 81, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 72, 15))
        self.label_12.setObjectName("label_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 10, 101, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 10, 93, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 40, 101, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(80, 70, 101, 21))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 72, 15))
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
        self.label_3.setText(_translate("MainWindow", "晶体输液量："))
        self.label_4.setText(_translate("MainWindow", "胶体输液量："))
        self.label_128.setText(_translate("MainWindow", "性别： "))
        self.label_129.setText(_translate("MainWindow", "年龄："))
        self.label_130.setText(_translate("MainWindow", "血压收缩压(mmHg)："))
        self.label_131.setText(_translate("MainWindow", "血压舒张压(mmHg)："))
        self.label_132.setText(_translate("MainWindow", "华氏温度(℉)："))
        self.label_133.setText(_translate("MainWindow", "高心率(bpm)："))
        self.label_134.setText(_translate("MainWindow", "低心率(bpm)："))
        self.label_135.setText(_translate("MainWindow", "动脉血压平均值(mmHg)："))
        self.label_136.setText(_translate("MainWindow", "二氧化碳分压(mmHg)："))
        self.label_137.setText(_translate("MainWindow", "氧分压(mmHg)："))
        self.label_138.setText(_translate("MainWindow", "尿素氮(mg/dL)："))
        self.label_139.setText(_translate("MainWindow", "胆红素(mg/dL)："))
        self.label_140.setText(_translate("MainWindow", "磷酸盐(mg/dL)："))
        self.label_141.setText(_translate("MainWindow", "氯化物(mEq/L)："))
        self.label_142.setText(_translate("MainWindow", "血细胞比容(%)："))
        self.label_143.setText(_translate("MainWindow", "肌酐(mg/dL)："))
        self.label_144.setText(_translate("MainWindow", "葡萄糖(mg/dL)："))
        self.label_145.setText(_translate("MainWindow", "血小板计数(K/uL)："))
        self.label_146.setText(_translate("MainWindow", "钙(mg/dL)："))
        self.label_147.setText(_translate("MainWindow", "钠(mmol/L)："))
        self.label_148.setText(_translate("MainWindow", "钾(mmol/L)："))
        self.label_149.setText(_translate("MainWindow", "镁(mg/dL)："))
        self.label_150.setText(_translate("MainWindow", "尿量(ml)："))
        self.label_151.setText(_translate("MainWindow", "男"))
        self.label_152.setText(_translate("MainWindow", "65"))
        self.label_153.setText(_translate("MainWindow", "153.8426724"))
        self.label_154.setText(_translate("MainWindow", "86.82794927"))
        self.label_155.setText(_translate("MainWindow", "100"))
        self.label_156.setText(_translate("MainWindow", "120"))
        self.label_157.setText(_translate("MainWindow", "60"))
        self.label_158.setText(_translate("MainWindow", "70"))
        self.label_159.setText(_translate("MainWindow", "29.8"))
        self.label_160.setText(_translate("MainWindow", "89.125"))
        self.label_161.setText(_translate("MainWindow", "122.2"))
        self.label_162.setText(_translate("MainWindow", "8.949999809"))
        self.label_163.setText(_translate("MainWindow", "7"))
        self.label_164.setText(_translate("MainWindow", "105"))
        self.label_165.setText(_translate("MainWindow", "34.72"))
        self.label_166.setText(_translate("MainWindow", "4.32"))
        self.label_167.setText(_translate("MainWindow", "171.2"))
        self.label_168.setText(_translate("MainWindow", "104.8"))
        self.label_169.setText(_translate("MainWindow", "4.395"))
        self.label_170.setText(_translate("MainWindow", "141.4"))
        self.label_171.setText(_translate("MainWindow", "3.575"))
        self.label_172.setText(_translate("MainWindow", "2.6"))
        self.label_173.setText(_translate("MainWindow", "7605"))
        self.label.setText(_translate("MainWindow", "安排输液后血钠预测值"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "mmol/L"))
        self.label_7.setText(_translate("MainWindow", "mL"))
        self.label_8.setText(_translate("MainWindow", "mL"))
        self.label_9.setText(_translate("MainWindow", "若不安排输液，血钠预测值为"))
        self.label_10.setText(_translate("MainWindow", "mmol/L"))
        self.label_11.setText(_translate("MainWindow", "149.41148"))
        self.label_12.setText(_translate("MainWindow", "患者ID:"))
        self.pushButton_2.setText(_translate("MainWindow", "确认ID"))
        self.label_13.setText(_translate("MainWindow", "住院ID:"))
        self.label_14.setText(_translate("MainWindow", "ICU-ID:"))

